name: Deployment front (PREPROD)

on:
  push:
    branches: [dev]

jobs:
  remove:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: remove existing folder front
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: "[ ! -e /srv/front/* ] || rm -r /srv/front/*"
          

  build:
    runs-on: ubuntu-latest
    environment: preprod
    needs: remove
    steps:
      - name: Download project from git
        uses: actions/checkout@v2

      - name: npm install
        run: npm i

      - name: Build project
        run: npm run build

      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    environment: preprod
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: ./build

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "build/*"
          TARGET: "/srv/front"

  restart-front:
    runs-on: ubuntu-latest
    environment: preprod
    needs: deploy
    steps:
      - name: restart pm2 front service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: "pm2 restart front"
